Verification Id added in certificate
open-certs/oc-backend pull request #22
Opened 2022-03-06 13:21 UTC by Simran2337

# Description:

Verification ID displayed on Certificate

Fixes #20

## Type of change:

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Screenshots / Video:
![image](https://user-images.githubusercontent.com/54612637/156925024-46594c8b-a227-4036-b4e2-65587ed9a25f.png)

2022-03-06 17:13 UTC, Shubham-Kumar-2000 requested changes

2022-03-06 17:13 UTC, Shubham-Kumar-2000 commented on src/views/certificate.ejs
> +            <div
- Put this in bottom left.
- Make ID readable like `67vj7-sdkvb-skvjs-sdkjv` add - after every 5 characters.

2022-03-06 17:13 UTC, Shubham-Kumar-2000 commented on src/views/certificate.ejs
> +                Id: <%= data._id %>
instead of `ID` use `Certificate Id` its more intent revealing.

2022-03-07 16:24 UTC, Simran2337 commented
@Shubham-Kumar-2000  changes made.
Can u please check and revert back?

2022-03-07 17:01 UTC, Shubham-Kumar-2000 requested changes

2022-03-07 17:01 UTC, Shubham-Kumar-2000 commented on src/views/certificate.ejs
> +            <div style="position: absolute; right: 50px; margin: 10px; margin-top: 23px; color: rgb(224 68 44); font-family: monospace;">
Remove the extra top margin.

2022-03-07 17:06 UTC, Shubham-Kumar-2000 approved these changes

2022-03-07 17:06 UTC, merged