Added recaptcha verification
open-certs/oc-backend pull request #33
Opened 2022-03-10 11:43 UTC by mdabdulshahed

# Description:

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue no.)

## Type of change:

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] My code follows the style guidelines of this project.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I have made corresponding changes to the documentation.
-   [ ] My changes generate no new warnings.
-   [ ] I have added tests that prove my fix is effective or that my feature works.
-   [ ] New and existing unit tests pass locally with my changes.
-   [ ] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video:

2022-03-10 12:01 UTC, Shubham-Kumar-2000 requested changes

2022-03-10 12:01 UTC, Shubham-Kumar-2000 commented on .husky/pre-commit
> -npm run format && npm test
undo changes in pre commit hook

2022-03-10 12:01 UTC, Shubham-Kumar-2000 commented on sample.env
> +
add empty line at the end of this line

2022-03-10 12:01 UTC, Shubham-Kumar-2000 commented on src/helpers/recaptcha.helper.js
> +exports.ValidateCaptcha = (req, res, next) => {
function names should start with lower case

2022-03-10 12:01 UTC, Shubham-Kumar-2000 commented on src/helpers/recaptcha.helper.js
> +exports.ValidateCaptcha = (req, res, next) => {
`ValidateCaptcha` => `validateReCaptcha`

2022-03-10 12:01 UTC, Shubham-Kumar-2000 commented on test/database.test.js
> -
undo changes in `database.test.js`

2022-03-10 16:25 UTC, mdabdulshahed commented on sample.env
> +
so 2 empty lines after bitbucket ?

2022-03-10 16:30 UTC, Shubham-Kumar-2000 commented on sample.env
> +
nope 1

2022-03-10 17:33 UTC, mdabdulshahed commented
Please check it once and let me know if any changes

2022-03-10 19:05 UTC, Shubham-Kumar-2000 requested changes

2022-03-10 19:05 UTC, Shubham-Kumar-2000 commented on .husky/pre-commit
> +npm run format && npm test
Always leave a empty line at the end of file

2022-03-10 19:05 UTC, Shubham-Kumar-2000 commented on test/database.test.js
> +});
Always leave a empty line at the end of file

2022-03-10 19:06 UTC, Shubham-Kumar-2000 commented
Also resolve conflicts.

2022-03-11 06:54 UTC, Shubham-Kumar-2000 approved these changes

2022-03-11 06:55 UTC, mdabdulshahed commented
Ready for merge

2022-03-11 06:55 UTC, merged