jwt access token encryption decryption
open-certs/oc-backend pull request #51
Opened 2022-03-30 07:34 UTC by MadhusreeBera

# Description:

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #13 

## Type of change:

-   [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

-   [X] My code follows the style guidelines of this project.
-   [X] I have performed a self-review of my own code.
-   [X] My changes generate no new warnings.
-   [X] Any dependent changes have been merged and published in downstream modules.

2022-03-30 14:51 UTC, Shubham-Kumar-2000 requested changes

2022-03-30 14:51 UTC, Shubham-Kumar-2000 commented on sample.env
> +ENCRYPTION_SECRET_KEY=XX
Add a blank line

2022-03-30 14:51 UTC, Shubham-Kumar-2000 commented on sample.test.env
> -TEST=YES
Revert this and run:
```
npm run quality
```
before committing.

2022-03-30 14:51 UTC, Shubham-Kumar-2000 commented on src/helpers/jwt.helper.js
> +                user.accessToken = decrypt(user.accessToken);
What happens if decrypt fails?

2022-03-30 15:17 UTC, Shubham-Kumar-2000 commented
@MadhusreeBera  please update the `PR` with the required changes.

2022-03-31 15:06 UTC, MadhusreeBera commented
I have made the required changes. Please check @Shubham-Kumar-2000

2022-03-31 17:58 UTC, Shubham-Kumar-2000 requested changes
Add test cases for `crypto.helper.js`

2022-04-01 16:53 UTC, Shubham-Kumar-2000 approved these changes

2022-04-01 16:53 UTC, merged