Separate Custom Error Handling.
open-certs/oc-backend pull request #62
Opened 2022-04-08 14:47 UTC by VRAJ9799

# Description:

I have separated the custom error handling from the Error Handler to CustomError.

Fixes #60 

## Type of change:

-   [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

-   [x] My code follows the style guidelines of this project.
-   [x] I have performed a self-review of my own code.
-   [x] My changes generate no new warnings.

2022-04-08 14:48 UTC, VRAJ9799 commented
Hi @Shubham-Kumar-2000 I created a PR please verify the change.

2022-04-08 18:58 UTC, Shubham-Kumar-2000 requested changes
Please run test cases before commit 
By running :
```bash
npm test
```

2022-04-08 18:58 UTC, Shubham-Kumar-2000 commented on src/helpers/errorhandler.helper.js
> +        err.handleError(res);
Return it from here.

2022-04-08 19:00 UTC, Shubham-Kumar-2000 commented
@VRAJ9799  please make necessary changes.

2022-04-09 06:13 UTC, Vraj9799 commented
Hi @Shubham-Kumar-2000 Can you please guide me about this error "const isDevelopment = req.app.get('env') === 'development';" i haven't changed anything here.

2022-04-09 06:16 UTC, Shubham-Kumar-2000 commented
@VRAJ9799  Join here https://meet.google.com/yun-diwh-whe

2022-04-09 08:03 UTC, Shubham-Kumar-2000 commented
Hi @VRAJ9799  I am dropping off please comment your available time. Will send a meet link at that time.

2022-04-10 11:56 UTC, VRAJ9799 commented
Hi @Shubham-Kumar-2000 I have push the changes.

2022-04-10 12:19 UTC, Shubham-Kumar-2000 approved these changes

2022-04-10 12:19 UTC, merged

2022-04-11 06:04 UTC, VRAJ9799 commented
Hi @Shubham-Kumar-2000 Can you please add gssoc tag so this pr can count for that ?

2022-04-11 09:34 UTC, Shubham-Kumar-2000 commented
Done @VRAJ9799  you can try other open issues.