Added Error handling logic for passport related errors
open-certs/oc-backend pull request #76
Opened 2022-09-06 16:39 UTC by AnshumanDubey1999

# Description:

Added Error handling logic for passport related errors

Fixes #63 

## Type of change:

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

2022-09-09 07:18 UTC, me-sk requested changes

2022-09-09 07:18 UTC, me-sk commented on src/errors/passport.error.js
> +            `${process.env.FRONTEND_URL}/recievedToken.html?errorType=${this.type}`
You also need to send error msg

2022-09-09 07:18 UTC, me-sk commented on src/controllers/auth.controller.js
> +    if (err) next(new PassportError(err.message));
Check if the error status is passport error status then only use this other wise just call the global error handler with whatever the error was

2022-09-09 07:18 UTC, me-sk commented on src/controllers/auth.controller.js
> +exports.errorHandler = (err, _req, _res, next) => {
also rename this fn

2022-09-16 15:03 UTC, Shubham-Kumar-2000 approved these changes

2022-09-16 15:03 UTC, merged